services:
  smtp-server:
    build:
      context: ./code/backends/freedom-mta-bridge
      args:
        - MAIL_DOMAIN=${MAIL_DOMAIN:-my-test.com}
    ports:
      - "25:25"  # SMTP
    environment:
      # Note: These variables do not work yet.
      # See the comment in bridge_incoming.js (need an intermediate file to pass them through)
      - MAIL_SERVER_HOST=mail-host
      - MAIL_SERVER_PORT=3000
    depends_on:
      - mail-host
    restart: unless-stopped

  mail-host:
    build: .
    environment:
      - PORT=3000
    env_file: .env
    restart: unless-stopped
