services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey_with_password
    command: valkey-server --requirepass supersecret
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  valkey_data:
