name: CI/CD

on:
  pull_request:
  push:
    branches:
      - main
      - draft/ci

jobs:
  ######################################################################################################################
  lint-all:
    name: Lint All

    runs-on: build-server
    defaults:
      run:
        working-directory: code

    steps:
      # Env setup
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
          cache-dependency-path: code/yarn.lock

      # Work Steps
      - name: 🔸 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🔸 Build Libraries
        run: yarn build-libs

      - name: 🔸 Type Check
        run: yarn build:tests

      - name: 🔸 Lint
        run: yarn lint

      - name: 🔸 Lint package.json Synchronization
        run: npx nx run freedom-dev-scripts:run:package-sync

  ######################################################################################################################
  test:
    name: Test

    runs-on: build-server
    defaults:
      run:
        working-directory: code

    steps:
      # Env setup
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
          cache-dependency-path: code/yarn.lock

      # Work Steps
      - name: 🔸 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🔸 Build Libraries
        run: yarn build-libs

      - name: 🔸 Test
        run: yarn test
